# Generated by Django 5.2.14 on 2026-05-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='house_logos/'),
        ),
    ]
