# Generated by Django 5.2.14 on 2026-05-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_house_customuser_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='onboarding_completed',
            new_name='questionnaire_completed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='school_email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Studente'), ('teacher', 'Docente'), ('teamleader', 'Team Leader'), ('admin', 'Admin')], max_length=20),
        ),
    ]
